[package]
name = "rvpacker-txt-rs"
version = "15.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["wrap_help", "cargo", "derive"] }
clap-verbosity-flag = { version = "3.0.4", default-features = false, features = [
    "tracing",
] }
encoding_rs = "0.8.35"
gxhash = { version = "3.5.0", features = ["deterministic"] }
rpgmad-lib = "5.0.0"
rvpacker-lib = { package = "rvpacker-txt-rs-lib", version = "15.0.0", path = "../rvpacker-txt-rs-lib" }
serde = "1.0.229"
serde_json = { version = "1.0.151", features = ["preserve_order"] }
strum = { version = "0.28.0", features = ["strum_macros"] }
tracing-subscriber = "0.3.23"
